services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: myproject.settings
      - key: PYTHON_VERSION
        value: 3.12.11
      - key: SECRET_KEY
        generateValue: true
    staticPublishPath: staticfiles
