# Generated by Django 5.1.2 on 2024-10-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('CourseId', models.AutoField(primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=50)),
                ('CoursePrice', models.CharField(max_length=50)),
                ('CourseDescription', models.TextField()),
                ('CourseDetails', models.TextField()),
                ('CourseImage', models.ImageField(upload_to='static/images/')),
            ],
        ),
    ]
