# Generated by Django 5.1.2 on 2024-10-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_delete_registereduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
